// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cduibtthxjwusgqnxtzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkdWlidHRoeGp3dXNncW54dHprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0Mzk0MTYsImV4cCI6MjA2MTAxNTQxNn0.wucgzgUhbGWGGnXfLxwZTS8H-g2ttqGxJP2zx_WrRl0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);